### ISSUE TITLE
Post meta fields

### ISSUE THREAD

**Issue by kittee** [caraheacock/the-unarmed-truth#2]
- [x] News Source (perhaps this should be a taxonomy)
- [x] Author
- [x] Link to original article
- [ ] Repeat articles (this story has appeared in other sources)
- [ ] Corrections
